:sparkles: refactor

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,48 +1,44 @@
-#!/bin/bash
-# vim:ft=sh
+#!/usr/bin/env fish
 
-if ! command -v fish &>/dev/null; then
-	echo "Error: Fish could not be found! Please install." 1>&2
-	exit 64
-fi
+if ! command -v fish &>/dev/null
+    echo "Error: Fish could not be found! Please install." 1>&2
+    exit 64
+end
 
-## prerequisites
-script_dir=$(dirname "$0")
-source $script_dir/__params
-source $script_dir/__var
+set -l DEST_PATH $HOME
+set -l LINK_PATH "$(dirname (dirname (realpath (status current-filename))))/links"
+set -l BACKUP_PATH $HOME/documents/throwaways/.backups/
 
-## symlink modules
-mkdir -pv "$log_dir"
-[ -f $symlink_logfile_file ] && : >"$symlink_logfile_file" # empty symlink log file
+set -l is_setup
+read -l -P 'Setup or Uninstall  dotfiles? [S/u] ' run_type
+switch $run_type
+    case '' S s
+        set is_setup true
+    case U u
+        set is_setup false
+    case '*'
+        echo -e 'Please select either setup or uninstall!\n'
+        return
+end
 
-mkdir -pv "$backup_dir"
-symlink_config() {
-	target=$1
-	dest=${2-$config_dir}
-	symlink_path="$dest/$(basename $target)"
+for link in (fd . 'dotfiles/links' --hidden --max-depth 1)
+    set -l target (readlink -f $link)
+    set -l dest $DEST_PATH
+    set -l target_name (basename $target)
+    set -l symlink_path "$dest/$target_name"
 
-	# remove exist symlinks
-	if [ -L $symlink_path ]; then
-		echo "Remove old symlink: $symlink_path"
-		rm $symlink_path &>/dev/null
+    echo
+    if [ -L $symlink_path ] # remove exist symlinks
+        echo "Remove old symlink: $symlink_path"
+		# unlink $symlink_path
 
-	# remove/backup exist configs
-	elif ([ -d $symlink_path ] || [ -f $symlink_path ]); then
-		echo "Backup: $symlink_path --> $backup_dir"
-		mv -v $symlink_path $backup_dir
-		rm -rf $symlink_path &>/dev/null
-	fi
+    else if [ -d $symlink_path ] || [ -f $symlink_path ] # remove/backup exist configs
+        set -l backup_path "$BACKUP_PATH$target_name--$(uuidgen --time)"
+        echo "Backup: $symlink_path --> $backup_path"
+		#mv $symlink_path $backup_path
+    end
 
-	echo "Set symlink: $target --> $symlink_path"
-	ln -sf $target $dest
-	echo $symlink_path >>"$symlink_logfile_file"
-}
 
-## configs in `modules` dir
-for entry in $(find $module_dir/ -maxdepth 1 ! -path $module_dir/); do
-	symlink_config $entry
-done
-
-symlink_config $extern_dir/.gitconfig $HOME # gitconfig
-symlink_config $extern_dir/.bashrc $HOME    # bash-shell
-symlink_config $extern_dir/.terminfo $HOME  # bash-shell
+    echo "Set symlink: $target --> $symlink_path"
+	#ln -sf $target $dest
+end
